FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ImageCompressor.Web.csproj", "./"]
RUN dotnet restore "ImageCompressor.Web.csproj"
COPY . .
RUN dotnet publish "ImageCompressor.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ImageCompressor.Web.dll"]